languageCode = "en-us"
defaultContentLanguage = "en"

enableRobotsTXT = true
enableEmoji = true

theme = "almeida-cv"

baseURL = "https://example.com/"
title = "Elyas Ebrahimpour Resume"

[params]
enableMetaTags = true
noindex = true
colorLight = "#eee"
colorDark = "#111"
colorPageBackground = "#111"
colorPrimary = "#e67e22"
colorSecondary = "#aaa"
colorIconPrimary = "#111111"
colorIconBackground = "#e67e22"
pages = 2
swapColumns = false

[languages]
[languages.en]
label = "English"
locale = "en-US"
direction = "ltr"
weight = 1
title = "Elyas Ebrahimpour - Resume"


[languages.fa]
label = "فارسی"
locale = "fa-IR"
direction = "rtl"
weight = 2
title = "الیاس ابراهیم پور - رزومه"
