locale = "en-us"
defaultContentLanguage = "en"

enableRobotsTXT = true
enableEmoji = true

theme = "almeida-cv"

baseURL = "https://elias-ebrahimpour.github.io/"

[params]
enableMetaTags = true
noindex = true
colorLight = "#F2F2F2"
colorDark = "#17130F"
colorPageBackground = "#17130F"
colorPrimary = "#e67e22"
colorSecondary = "#A9A29A"
colorIconPrimary = "#17130F"
colorIconBackground = "#e67e22"
pages = 2
swapColumns = false

[languages]
[languages.en]
contentDir = "content/en"
label = "English"
locale = "en-US"
direction = "ltr"
weight = 1
title = "Elyas Ebrahimpour"


[languages.fa]
contentDir = "content/fa"
label = "فارسی"
locale = "fa-IR"
direction = "rtl"
weight = 2
title = "الیاس ابراهیم پور"
